Repository magma/ci-management, pull requests merged in 2021-09, with the labels that each got.

#41 chore: Add bigger instance size to test performance of integ tests
  jenkins-config/clouds/openstack/vex/ubuntu2004-docker-16c-64g.cfg
Labels: size/XS

#40 refactor: Migrate cwag pipelines
  jenkins-config/clouds/openstack/vex/ubuntu2004-docker-8c-32g.cfg
  jjb/cwag/cwag-integration-templates.yaml
  jjb/cwag/cwag-integration.yaml
Labels: size/M

#43 Fix: Add missing properties
  jjb/cwag/cwag-integration-templates.yaml
Labels: size/XS

#44 Fix: Add main magma tab
  jjb/cwag/cwag-integration.yaml
  jjb/magma/magma-cwag-integration-templates.yaml
  jjb/magma/magma-jobs.yaml
Labels: size/S

#45 Refactor: Migrate vagrant pipelines
  jjb/magma/magma-jobs.yaml
  jjb/magma/magma-vagrant-templates.yaml
Labels: size/M
